app:
    hostname: localhost
    port: 80
    debug_verbose: false
    item_price_service:
        allow_city_only: false

postgres:
    hostname: hostname
    port: 5432
    user: username
    password: password
    db_name: database_name
    pool_size: 25
