app:
    hostname: localhost
    port: 80
    item_price_service:
        allow_city_only: true

postgres:
    hostname: hostname
    port: 5432
    user: username
    password: password
    db_name: database_name
